name: Swift CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.9

    steps:
    - uses: actions/checkout@v4

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  platform-builds:
    name: Build for all platforms
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build for macOS
      run: swift build --arch x86_64 --arch arm64

    - name: Build for iOS Simulator
      run: xcodebuild build -scheme ServiceContainer -sdk iphonesimulator -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO

    - name: Build for tvOS Simulator
      run: xcodebuild build -scheme ServiceContainer -sdk appletvsimulator -destination "generic/platform=tvOS Simulator" CODE_SIGNING_ALLOWED=NO

    - name: Build for watchOS Simulator
      run: xcodebuild build -scheme ServiceContainer -sdk watchsimulator -destination "generic/platform=watchOS Simulator" CODE_SIGNING_ALLOWED=NO
      continue-on-error: true