name: Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test iOS & macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Swift version
      run: swift --version

    - name: Build for macOS
      run: swift build

    - name: Run tests on macOS
      run: swift test

    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -scheme ServiceContainer \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" \
          CODE_SIGNING_ALLOWED=NO

    - name: Run tests on iOS Simulator
      run: |
        xcodebuild test \
          -scheme ServiceContainer \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" \
          CODE_SIGNING_ALLOWED=NO \
          -quiet